clear_filter_reminder:
  target:
    entity:
      integration: lunos
      domain: fan

turn_on_summer_ventilation:
  target:
    entity:
      integration: lunos
      domain: fan

turn_off_summer_ventilation:
  target:
    entity:
      integration: lunos
      domain: fan
